# Generated by Django 3.0 on 2020-01-04 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('company', models.CharField(max_length=1024, verbose_name='Name of the Company')),
                ('intern', models.CharField(choices=[('1', '1'), ('2', '2-4'), ('3', '5-10'), ('4', '10+')], default='1', max_length=6, verbose_name='Number of Interns')),
                ('job', models.TextField(max_length=1024, verbose_name='Job Description')),
                ('timeperiod', models.CharField(choices=[('1', 'Summer Vacations (May - July)'), ('2', 'Winter Vacations (December - Mid-January'), ('3', 'Other (Only Work From Home Interns available)')], default='1', max_length=100, verbose_name='Time period when you want the intern')),
                ('stipend', models.CharField(max_length=1024, verbose_name='Tentative stipend (per month)')),
                ('hiring', models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Maybe')], default='1', max_length=10, verbose_name='Are you interested in hiring permanent employees also?')),
                ('requirements', models.TextField(max_length=1024, verbose_name='Specific requirements (Like college or stream of candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
