# Generated by Django 2.0.13 on 2020-04-07 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_auto_20200104_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hiring',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='stipend',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='timeperiod',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='achievemennts',
            field=models.TextField(max_length=1024, null=True, verbose_name='Personal Achievements'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cgpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='CGPA (0.00 - 10.00)'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='college',
            field=models.CharField(max_length=1024, null=True, verbose_name='Name of the College'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.TextField(max_length=1024, null=True, verbose_name='Preferred Job Profile'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
