# Generated by Django 2.0.13 on 2020-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200407_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='achievemennts',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.TextField(max_length=1024, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
