# Generated by Django 2.0.13 on 2020-04-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200410_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo1',
            name='highschool',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='hscityandstate',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='hspercentage',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='hsyear',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='sscityandstate',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='sspercentage',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='ssschool',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='ssyear',
        ),
    ]
