# Generated by Django 2.0.13 on 2020-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200413_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='fathersoccupation',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='finalyear',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='graduate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='polytechnic',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='twelfth',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
