# Generated by Django 2.0.13 on 2020-04-13 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20200413_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='college',
            field=models.CharField(max_length=1024, null=True, verbose_name='Name of the College'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='communication',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='finalyear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='percentage',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='polytechnic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twelfth',
            field=models.BooleanField(default=False),
        ),
    ]
