# Generated by Django 2.0.13 on 2020-04-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200412_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job.Job'),
        ),
    ]
