# Generated by Django 2.0.13 on 2020-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_checkbox_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbox',
            name='choice',
            field=models.BooleanField(),
        ),
    ]
