# Generated by Django 2.0.13 on 2020-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200412_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbox',
            name='choice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
