# Generated by Django 2.0.13 on 2020-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20200412_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbox',
            name='choice',
            field=models.BooleanField(default=False),
        ),
    ]
