# Generated by Django 2.0.13 on 2020-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200412_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='choice',
            new_name='choice1',
        ),
        migrations.RemoveField(
            model_name='checkbox',
            name='company',
        ),
        migrations.AddField(
            model_name='checkbox',
            name='choice2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkbox',
            name='choice3',
            field=models.BooleanField(default=False),
        ),
    ]
