# Generated by Django 2.0.13 on 2020-04-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200412_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
