# Generated by Django 2.0.13 on 2020-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='choice4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkbox',
            name='choice5',
            field=models.BooleanField(default=False),
        ),
    ]
